
package nmsvrscreenshotfix;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class ProgramUI extends javax.swing.JFrame {

    LogicController controller = LogicController.getInstance();
    
    public ProgramUI() {
        initComponents();
        resultFolderField.setText(controller.resultPath);
        sourceFolderField.setText(controller.sourcePath);
        behaviorTextArea.setText(controller.getCurrentBehavior());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourceFolderField = new javax.swing.JTextField();
        sourceFolderButton = new javax.swing.JButton();
        resultFolderField = new javax.swing.JTextField();
        resultFolderButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        behaviorTextArea = new javax.swing.JTextArea();
        settingsButton = new javax.swing.JButton();
        executeButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NMS VR Screenshot Fix");
        setResizable(false);

        jLabel2.setText("Source Folder:");

        jLabel1.setText("Behavior:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Result Folder:");

        sourceFolderField.setText("err");
        sourceFolderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceFolderFieldActionPerformed(evt);
            }
        });

        sourceFolderButton.setText("...");
        sourceFolderButton.setMaximumSize(new java.awt.Dimension(22, 22));
        sourceFolderButton.setMinimumSize(new java.awt.Dimension(22, 22));
        sourceFolderButton.setPreferredSize(new java.awt.Dimension(32, 32));
        sourceFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceFolderButtonActionPerformed(evt);
            }
        });

        resultFolderField.setText("err");
        resultFolderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFolderFieldActionPerformed(evt);
            }
        });

        resultFolderButton.setText("...");
        resultFolderButton.setMaximumSize(new java.awt.Dimension(22, 22));
        resultFolderButton.setMinimumSize(new java.awt.Dimension(22, 22));
        resultFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFolderButtonActionPerformed(evt);
            }
        });

        behaviorTextArea.setEditable(false);
        behaviorTextArea.setColumns(20);
        behaviorTextArea.setLineWrap(true);
        behaviorTextArea.setRows(5);
        behaviorTextArea.setText("• Make copies of converted screenshots\n• Add prefix \" new_\" to the new image\n• Ex: \"image.png\" -> \"new_image.png\"\n");
        jScrollPane2.setViewportView(behaviorTextArea);

        settingsButton.setText("Behavior Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(executeButton)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(settingsButton)
                    .addComponent(sourceFolderField)
                    .addComponent(resultFolderField)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourceFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultFolderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(273, 273, 273))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(sourceFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceFolderField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        if(controller.isExecuting) {
            controller.cancelExecution();
            toggleUI();
        } 
        else {
            controller.sourcePath = sourceFolderField.getText();
            controller.resultPath = resultFolderField.getText();
            if (controller.hasValidDirectoryPaths()) {
                controller.execute();
                toggleUI();
            }
            else {
                JOptionPane.showMessageDialog(this,
                    "One of the paths appears to not be a valid folder","Error",
                    JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_executeButtonActionPerformed

    private void toggleUI() {
        boolean shouldEnable = !controller.isExecuting;
        settingsButton.setEnabled(shouldEnable);
        sourceFolderField.setEnabled(shouldEnable);
        sourceFolderButton.setEnabled(shouldEnable);
        resultFolderField.setEnabled(shouldEnable);
        resultFolderButton.setEnabled(shouldEnable);
        
        if(controller.isExecuting) {executeButton.setText("cancel");}
        else {executeButton.setText("execute");}
    }
    
    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        new SettingsUI(this,true).setVisible(true);
        behaviorTextArea.setText(controller.getCurrentBehavior());
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void sourceFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceFolderButtonActionPerformed
        JFileChooser jfc = new JFileChooser(); 
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
        int optionCode = jfc.showSaveDialog(null); 
        
        if (optionCode == JFileChooser.APPROVE_OPTION) {
            controller.sourcePath = jfc.getSelectedFile().getAbsolutePath();
            sourceFolderField.setText(controller.sourcePath);
            behaviorTextArea.setText(controller.getCurrentBehavior());
        }
    }//GEN-LAST:event_sourceFolderButtonActionPerformed

    private void resultFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFolderButtonActionPerformed
        JFileChooser jfc = new JFileChooser(); 
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
        int optionCode = jfc.showSaveDialog(null); 
        
        if (optionCode == JFileChooser.APPROVE_OPTION) {
            controller.resultPath = jfc.getSelectedFile().getAbsolutePath();
            resultFolderField.setText(controller.resultPath);
            behaviorTextArea.setText(controller.getCurrentBehavior());
        }
    }//GEN-LAST:event_resultFolderButtonActionPerformed

    private void sourceFolderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceFolderFieldActionPerformed
        controller.sourcePath = sourceFolderField.getText();
        behaviorTextArea.setText(controller.getCurrentBehavior());
    }//GEN-LAST:event_sourceFolderFieldActionPerformed

    private void resultFolderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFolderFieldActionPerformed
        controller.resultPath = resultFolderField.getText();
        behaviorTextArea.setText(controller.getCurrentBehavior());
    }//GEN-LAST:event_resultFolderFieldActionPerformed

    public void updateProgressBar(int value) {
        progressBar.setValue(value);
    }
    
    public void successPopup(int value) {
        JOptionPane.showMessageDialog(this,
            ("Converted " + value + " images successfully."),"Complete",
            JOptionPane.INFORMATION_MESSAGE);
        progressBar.setValue(0);
    }
    
    public void cancelPopup(int value) {
        JOptionPane.showMessageDialog(this,
            "Converted " + value + " files before canceling.","Canceled",
            JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea behaviorTextArea;
    private javax.swing.JButton executeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton resultFolderButton;
    private javax.swing.JTextField resultFolderField;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton sourceFolderButton;
    private javax.swing.JTextField sourceFolderField;
    // End of variables declaration//GEN-END:variables
}
