/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmsvrscreenshotfix;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author midli
 */
public class SettingsUI extends javax.swing.JDialog {

    LogicController controller = LogicController.getInstance();
    
    
    public SettingsUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if(controller.shouldRename) {renameButton.setSelected(true);}
        else {dontRenameButton.setSelected(true);}
        if(controller.renameNewFile) {renameNewButton.setSelected(true);}
        else {renameOriginalButton.setSelected(true);}
        addTextField.setText(controller.addToFile);
        if(controller.addAsPrefix) {prefixButton.setSelected(true);}
        else {suffixButton.setSelected(true);}
        
        if(dontRenameButton.isSelected()) {disableRenamePanel(newFileSettings);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replaceOrCopyGroup = new javax.swing.ButtonGroup();
        renameWhichGroup = new javax.swing.ButtonGroup();
        prefixOrSuffix = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dontRenameButton = new javax.swing.JRadioButton();
        renameButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ConfirmButton = new javax.swing.JButton();
        newFileSettings = new javax.swing.JPanel();
        renameNewButton = new javax.swing.JRadioButton();
        renameOriginalButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prefixButton = new javax.swing.JRadioButton();
        suffixButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        addTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setModal(true);
        setResizable(false);

        replaceOrCopyGroup.add(dontRenameButton);
        dontRenameButton.setText("Keep Same Names");
        dontRenameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontRenameButtonActionPerformed(evt);
            }
        });

        replaceOrCopyGroup.add(renameButton);
        renameButton.setText("Edit File Names");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Rename files?");

        ConfirmButton.setText("confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        renameWhichGroup.add(renameNewButton);
        renameNewButton.setText("Converted File");
        renameNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameNewButtonActionPerformed(evt);
            }
        });

        renameWhichGroup.add(renameOriginalButton);
        renameOriginalButton.setText("Original File");
        renameOriginalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameOriginalButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Rename which file?");

        jLabel7.setText("Add as a prefix or suffix?");

        prefixOrSuffix.add(prefixButton);
        prefixButton.setText("Add Prefix");
        prefixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixButtonActionPerformed(evt);
            }
        });

        prefixOrSuffix.add(suffixButton);
        suffixButton.setText("Add Suffix");
        suffixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suffixButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Text to be added:");

        addTextField.setText("_new");
        addTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newFileSettingsLayout = new javax.swing.GroupLayout(newFileSettings);
        newFileSettings.setLayout(newFileSettingsLayout);
        newFileSettingsLayout.setHorizontalGroup(
            newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newFileSettingsLayout.createSequentialGroup()
                .addGroup(newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(renameOriginalButton)
                    .addComponent(prefixButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(renameNewButton)
                    .addComponent(suffixButton))
                .addGap(35, 35, 35))
            .addGroup(newFileSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        newFileSettingsLayout.setVerticalGroup(
            newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newFileSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addGroup(newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(renameOriginalButton)
                    .addComponent(renameNewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(newFileSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(prefixButton)
                    .addComponent(suffixButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(newFileSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dontRenameButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(renameButton)
                                        .addGap(35, 35, 35))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(ConfirmButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dontRenameButton)
                    .addComponent(renameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFileSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dontRenameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontRenameButtonActionPerformed
        disableRenamePanel(newFileSettings);
        controller.shouldRename = false;
    }//GEN-LAST:event_dontRenameButtonActionPerformed

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        enableRenamePanel(newFileSettings);
        controller.shouldRename = true;
    }//GEN-LAST:event_renameButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        if (controller.isValidAddition(addTextField.getText())) {
            controller.addToFile = addTextField.getText();
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this,
                    "Text can only contain alphanumeric characters, '_' and '-'.","Error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void renameNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameNewButtonActionPerformed
        controller.renameNewFile = true;
    }//GEN-LAST:event_renameNewButtonActionPerformed

    private void prefixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixButtonActionPerformed
        controller.addAsPrefix = true;
    }//GEN-LAST:event_prefixButtonActionPerformed

    private void addTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextFieldActionPerformed
        // no action
    }//GEN-LAST:event_addTextFieldActionPerformed

    private void renameOriginalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameOriginalButtonActionPerformed
        controller.renameNewFile = false;
    }//GEN-LAST:event_renameOriginalButtonActionPerformed

    private void suffixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suffixButtonActionPerformed
        controller.addAsPrefix = false;
    }//GEN-LAST:event_suffixButtonActionPerformed
    
    private void disableRenamePanel(JPanel panel){
        panel.setEnabled(false);
        Component[] components = panel.getComponents();
        
        for (Component component : components) {
            if (component instanceof JPanel) {
                disableRenamePanel((JPanel) component);
            }
            component.setEnabled(false);
        }
    }
    
    private void enableRenamePanel(JPanel panel){
        panel.setEnabled(true);
        Component[] components = panel.getComponents();
        
        for (Component component : components) {
            if (component instanceof JPanel) {
                disableRenamePanel((JPanel) component);
            }
            component.setEnabled(true);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextField addTextField;
    private javax.swing.JRadioButton dontRenameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel newFileSettings;
    private javax.swing.JRadioButton prefixButton;
    private javax.swing.ButtonGroup prefixOrSuffix;
    private javax.swing.JRadioButton renameButton;
    private javax.swing.JRadioButton renameNewButton;
    private javax.swing.JRadioButton renameOriginalButton;
    private javax.swing.ButtonGroup renameWhichGroup;
    private javax.swing.ButtonGroup replaceOrCopyGroup;
    private javax.swing.JRadioButton suffixButton;
    // End of variables declaration//GEN-END:variables
}
